# This is a basic workflow to help you get started with Actions

name: CI/CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: 
      - betaRelease
      - dev
      - master

# Variables that are available for all the jobs in the workflow
env:
  DEPLOYMENT_SCRIPT: 'test.ps1'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checkout code
    - name: Checkout code
      uses: actions/checkout@v2
        
    # upload deployment script    
    - name: Upload deployment script
      uses: actions/upload-artifact@v2
      with:
        name: deploymentScript
        path: ${{env.DEPLOYMENT_SCRIPT}} 

  deploy:
    # The type of runner that the job will run on
    runs-on: windows-latest
    needs: [build]
    env:
      SITES: 'BetaBranch'
   
    steps:       
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.5
        with:
          name: deploymentScript
          path: deploymentScript
          
      - name: Run script to install PnP Powershell and deploy app on site using PnP Powershell
        run: deploymentScript/${{env.DEPLOYMENT_SCRIPT}}
        shell: powershell
